runtime: nodejs16

env_variables:
  API_URL: ${_API_URL}

handlers:
  # Serve all static files with urls ending with a file extension
  - url: /(.*\..+)$
    static_files: \1
    upload: (.*\..+)$
    secure: always

  # Catch all handler to index.html
  - url: /.*
    static_files: index.html
    upload: index.html
    secure: always

instance_class: F1