steps:
  # Step 1: Install dependencies and build
  - name: 'node:16'
    entrypoint: npm
    args: ['install']
    dir: 'frontend'

  # Step 2: Replace environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        cat > frontend/js/env.js << 'EOF'
        window._env_ = {
          API_URL: "${_API_URL}",
        };
        export const updateEnv = (env) => {
          window._env_ = { ...window._env_, ...env };
        };
        EOF

  # Step 3: Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - app
      - deploy
      - app.yaml
      - '--quiet'
    dir: 'frontend'

options:
  logging: CLOUD_LOGGING_ONLY  # Opsional: hanya mencatat log ke Google Cloud Logging